---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reception
  labels:
    app: reception
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reception
  template:
    metadata:
      labels:
        app: reception
    spec:
      containers:
        - name: reception
          image: username/reception:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: diagnosis
  labels:
    app: diagnosis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diagnosis
  template:
    metadata:
      labels:
        app: diagnosis
    spec:
      containers:
        - name: diagnosis
          image: username/diagnosis:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: examination
  labels:
    app: examination
spec:
  replicas: 1
  selector:
    matchLabels:
      app: examination
  template:
    metadata:
      labels:
        app: examination
    spec:
      containers:
        - name: examination
          image: username/examination:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: management
  labels:
    app: management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: management
  template:
    metadata:
      labels:
        app: management
    spec:
      containers:
        - name: management
          image: username/management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: reception
  labels:
    app: reception
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: reception


---


apiVersion: v1
kind: Service
metadata:
  name: diagnosis
  labels:
    app: diagnosis
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: diagnosis


---


apiVersion: v1
kind: Service
metadata:
  name: examination
  labels:
    app: examination
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: examination


---


apiVersion: v1
kind: Service
metadata:
  name: management
  labels:
    app: management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: management

