apiVersion: apps/v1
kind: Deployment
metadata:
  name: reception
  labels:
    app: reception
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reception
  template:
    metadata:
      labels:
        app: reception
    spec:
      containers:
        - name: reception
          image: pyodol2/reception:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
